### ISSUE TITLE
디자인 이슈

### ISSUE THREAD

**Issue by gene63** [heavencandle/cose490_memo#10]
CSS 담당인 제가 디자인 감각이 너무 부족하여 issue에서 함께 토론하여 색상을 정해볼까 합니다.
현재 까지 완료된 저희 웹사이트의 디자인은 아래와 같습니다. (색깔은 임의로 선정하였습니다!)

![image](https://user-images.githubusercontent.com/34651994/120473750-51f57c80-c3e2-11eb-9728-6e2de682d6c2.png)

위 화면 이미지에서 더 바뀌었으면 좋겠는 디자인이나 배경색 등의 아이디어가 있다면 자유롭게 적어주시면 감사하겠습니다!
적극적인 의견 제시 부탁드립니다!!

**Comment by gene63** [comment]
저는 개인적으로 general zone에 있는 pin icon은 검은색으로 두고 pinned zone에 있는 pin icon을 빨간색으로 하여 고정되었음을 표시해주고 싶습니다. 다만, 그렇게 구현하려면 현재 single-note로 같은 className을 쓰고 있는 구조를 수정하여 general zone과 pinned zone 에 들어가는 single-note가 분리된 class를 가질 수 있게 구현해야 할 것 같습니다! @heavencandle 님, 혹시 이러한 구조의 수정이 가능할까요??

**Comment by KULEEEE** [comment]
General zone은 얼티메이트 그레이 (#939597 / 147 149 151), Pinned zone은 일루미네이팅 (#F5DF4D / 245 223 77)로 설정하면 예쁠거 같아요 나머지 디자인은 생각나는것 있으면 계속하여 올려보겠습니다!! 감사합니다. (괄호 안 왼쪽은 HEX코드, 오른쪽은 RGB 값을 적어놓았습니다.)

**Comment by gene63** [comment]
@KULEEEE 피드백 감사합니다!! 재연님의 피드백 반영한 화면입니다!
![image](https://user-images.githubusercontent.com/34651994/120476253-54a5a100-c3e5-11eb-88a2-6231d68e56cb.png)
다른 분들도 많은 의견 부탁드립니다 ㅎㅎ

**Comment by KULEEEE** [comment]
반영 감사합니다!! 추가로 메모에 있는 버튼 색 우선 투명으로 바꾸면 괜찮을 것 같습니다!!

**Comment by heavencandle** [comment]
회의 때 사용한 레퍼런스 아카이빙 해 두겠습니다~

![image](https://user-images.githubusercontent.com/62787552/120506978-6301b600-c401-11eb-8491-684f63bc748e.png)
