### ISSUE TITLE
[UI/UX] Design Reference

### ISSUE THREAD

**Issue by heavencandle** [heavencandle/cose490_memo#13]
다른 선호하시는 디자인 있으면 해당 이슈에 아카이빙 해주세요 :0

![image](https://user-images.githubusercontent.com/62787552/120508417-a90b4980-c402-11eb-9913-2ef0898a7d5d.png)

![image](https://user-images.githubusercontent.com/62787552/120508449-b1638480-c402-11eb-9db4-6c67d481a606.png)

https://www.pinterest.co.kr/pin/485544403583956903/
https://www.pinterest.co.kr/pin/441563938464929037/
pinterest.co.kr/pin/137008013653899234/
https://www.pinterest.co.kr/pin/351351208433683177/

**Comment by gene63** [comment]
기본 기능 구현이 어느정도 완료한 후에 디자인을 고민할 때 참고하겠습니다!
좋은 소스 주셔서 감사합니다!!
