### ISSUE TITLE
[멘토링] 멘토링 줌 링크_210603

### ISSUE THREAD

**Issue by heavencandle** [heavencandle/cose490_memo#15]
https://korea-ac-kr.zoom.us/j/82721201615?pwd=MCtxYndabE9aeWNNTUh4aDJhQWJSdz09

**Comment by heavencandle** [comment]
**[데이터 저장에 대한 부분]**
- 웹 스토리지의 사용 / DB 사용
- 브라우저에서 persistent 하게 / 로컬 스토리지에 저장
- firebase, 네이버 클라우드 측이 이야기해서 임시 계정을 받아서 장비를 사용할 수도 있음

**[UI]**
- 기존 UI, 복잡하지 않게 적용할 방법
- material -> react에 적용하기 좋음

**[PR]**
- 적어도 한 사람이 approve 하면 merge할 수 있도록 기능 설정하기

**Comment by mentalese** [comment]
프로젝트 평가 요소에 문서화도 있는것 같습니다.

README.md 를 작성해서 프로젝트에 대한 소개를 하면 좋을것 같습니다. 
- 어떤 목적을 위해 만들어 졌는지?
- 어떤 기술스택을 사용하는지?
- 프로젝트 참여 인원

등이 포함되면 좋을것 같습니다.
