### ISSUE TITLE
[UI/UX] TodoNote와 plainNote가 정렬되지 않는 문제

### ISSUE THREAD

**Issue by gene63** [heavencandle/cose490_memo#20]
아래의 이미지처럼 TodoNote가 plainNote보다 아래쪽에 위치하다가 항목을 입력하면 위쪽으로 올라가는 에러가 있습니다!
![image](https://user-images.githubusercontent.com/34651994/120911339-b3a73680-c6c1-11eb-846b-ebe6e3ed4d3b.png)

혹시 해결법에 대한 아이디어가 있으신 분들은 말씀해주시면 감사하겠습니다!

**Comment by heavencandle** [comment]
지금은 해결된 이슈이지만, 공유를 위해 남겨놓습니다 :)

내부 element overflow 때문에 todo 추가할 때마다 옆에 노트가 아래로 밀렸던 것이었고,
overflow 속성 적용하면 해결할 수 있습니다. 
![Uploading image.png…]()
