### ISSUE TITLE
Where to initialize status

### ISSUE THREAD

**Issue by ksj4654** [heavencandle/cose490_memo#22]
최초 웹페이지를 열었을 때 default로 메모를 2~3개 띄워놓는 작업을 진행중입니다.

저희 구조가 General 및 Pinned 라는 이름의 status에  메모들을 저장해놓는 구조여서 최초 페이지 실행시 status를 초기화 시키는 방법을 찾고 있었습니다.

보통 App을 class형태로 정의해서 constructor를 이용해 초기화를 하는데

저희는 현재 App.js를 function 형태로 사용하고 있어서 이를 어떻게 초기화 해야할지 방법을 찾고있습니다.

조언 부탁드립니다!!

**Comment by heavencandle** [comment]
세진님 AppUtils 파일에서 위 코드를 아래로 바꿔보실래요?_?
테스트 코드로 적어본거라, 실제 하실 때에는 for 사용하시면 좋을 것 같습니다 :)

```const [general, setGeneral] = useState([]); ```

```
const [general, setGeneral] = useState([
      {id: uuid(), notetype:'plain'},
      {id: uuid(), notetype:'plain'},
      {id: uuid(), notetype:'plain'},
      {id: uuid(), notetype:'plain'},
      {id: uuid(), notetype:'plain'}
    ]);```
