### ISSUE TITLE
[SingleNote] Default Design

### ISSUE THREAD

**Issue by ksj4654** [heavencandle/cose490_memo#27]
![image](https://user-images.githubusercontent.com/67813034/121853895-7596bc00-cd2c-11eb-83e4-d024dbe64ced.png)
디자인을 위해 초기에 총 6개의 메모를 노출시키기로 했는데
막상 해보니 모든 노트에 같은 시간이 박혀있어서 뭔가 애매해진 느낌입니다.
이에대해 의견 남겨주시면 감사하겠습니다!!

**Comment by KangHyunSub** [comment]
처음에 노출되어 있는 것이라서 같은 시간이 박혀있어도 괜찮을 것 같습니다.

**Comment by gene63** [comment]
저는 꼭 초기에 노트가 노출될 필요가 없다고 생각합니다만, 해당 문제는 후에 json으로 메모들의 내용을 저장하고 불러오는 기능이 구현되면 기존 메모 내용을 보여주면 되기에 자동으로 해결 될 것으로 보입니다!

**Comment by heavencandle** [comment]
>해당 문제는 후에 json으로 메모들의 내용을 저장하고 불러오는 기능이 구현되면 기존 메모 내용(각기 다른 날짜에 작성된 내용)을 보여주면 되기에 자동으로 해결 될 것으로 보입니다!

샘플 데이터가 있을 경우에는 그렇겠지만, 사용자가 처음 사용하는 상황을 가정하면 고민해 볼 필요는 있을 것 같아요.
개발하면서 거슬리는지 확인해보면 좋을 것 같아서 아직 이슈 닫지는 않겠습니다!
