### ISSUE TITLE
[SingleNote] Translate button

### ISSUE THREAD

**Issue by ksj4654** [heavencandle/cose490_memo#28]
초기에 SingleNote에 번역버튼(Lang) 구현했었는데 개발이 진행되면서 단어장 템플릿에만 번역기능을 구현하기로 하니

다른 노트에는 Lang 버튼이 필요가 없어진 것 같습니다.

그럼 단어장 템플릿에서 어떤 동작시 번역기능을 동작하도록 하는게 좋을까요?

예를들어 단어장 템플릿에만 Lang버튼을 만들고 누르면 모든 단어에 대해 Meaning이 번역되어 입력된다던지

각 줄마다 버튼을 만든다던지

Enter를 눌러서 새로운 단어를 추가할 때 자동으로 번역되서 저장된다던지....

의견 부탁드립니다!!

**Comment by heavencandle** [comment]
1. 저는 다른 템플릿에는 없어도 될 것 같아요
2. 지금처럼 노트 하나에 번역 버튼을 하나 두고, 누르면 모든 단어에 대한 뜻을 자동입력하는 방향에 한표요!

**Comment by ksj4654** [comment]
![image](https://user-images.githubusercontent.com/67813034/121857505-a7aa1d00-cd30-11eb-9b5d-dcfd63487549.png)
Vocab.js에 버튼을 만드니 버튼이 아래에 생깁니다. 핀아이콘 있는 줄은 SingleNote영역이라....
이거 혹시 어떻게 올리죠

**Comment by KangHyunSub** [comment]
다른 템플릿에는 번역 기능이 불필요 한 것 같고, 단어장 템플릿에는 한번에 모든 단어의 뜻을 번역하는 것이 좋을 것 같습니다!

**Comment by KULEEEE** [comment]
저 또한 다른 템플릿에는 필요 없을 듯 합니다. 감사합니다!!

**Comment by gene63** [comment]
다른 분들의 의견 확인했습니다! 단어장 템플릿을 제외하고는 lang 버튼을 없애도록 하겠습니다!
이 task는 각 노트를 설계해주신 @heavencandle 님과 css를 담당하는 제가 맡으면 좋을 것 같습니다!
제가 맡아서 진행해볼까요?? @heavencandle

**Comment by heavencandle** [comment]
>이 task는 각 노트를 설계해주신 @heavencandle 님과 css를 담당하는 제가 맡으면 좋을 것 같습니다!
이 부분은 조건부로 노출하기로 PR에서 논의 완료했고,

>버튼을 누르면 모든 단어의 뜻이 번역되도록 하는 기능
번역 관련 기능은 세진님께서 진행해주셨습니다.

@gene63  확인하시면 이슈 닫겠습니다 :)

**Comment by gene63** [comment]
확인했습니다!

**Comment by heavencandle** [comment]
번역 버튼을 사용하는 대신, 아래처럼 세진님과 협의 했습니다.
아래와 같이 진행하면, 번역 버튼을 사용하지 않아도 될 듯 해서 issue 닫겠습니다!

1. 사용자가 번역하고자 하는 Word 입력, Meaning 칸은 삭제
(_이전 ver: 사용자가 번역하고자 하는 Word를 작성하고 meaning 칸에서 엔터하면 추가_)
2. 엔터 누르면 번역 실행
3. Word와 번역된 내용(meaning)을 Vocab Item으로서 노출
