### ISSUE TITLE
[vocabUtils] 번역해서 변경한 state가 화면에 반영되지 않는 문제

### ISSUE THREAD

**Issue by ksj4654** [heavencandle/cose490_memo#29]
![image](https://user-images.githubusercontent.com/67813034/122006211-88bf8f80-cdf1-11eb-9fa1-eb7dafa93fc2.png)
vocab.word를 번역해서 vocab.meaning에 저장한 다음 state를 변경하였습니다.
![image](https://user-images.githubusercontent.com/67813034/122006300-9f65e680-cdf1-11eb-9358-f031fc30e4cd.png)
그런데 다음 사진처럼 vocab자체는 잘 변경된 것 같은데 화면에 내용이 반영이 되지 않습니다.
setState를 잘못한 것인지, state변경이 반영이 안되는 건지 잘 모르겠습니다.
의견부탁드립니다.

**Comment by heavencandle** [comment]
#34 멘토님 피드백 주신 내용 있고,
#35 세진님이 해당 내용 반영, 수정 완료하여 이슈 닫습니다~
