### ISSUE TITLE
Api호출시 CORS에러발생

### ISSUE THREAD

**Issue by ksj4654** [heavencandle/cose490_memo#4]
![image](https://user-images.githubusercontent.com/67813034/120324205-53ab3b80-c321-11eb-8b12-3e44633a6277.png)

네이버 파파고 오픈 api 호출코드 작성 중 생긴 문제입니다.

아마 로컬 개발환경에서 작업하는 중이라 도메인이 일치하지 않아서 생기는 문제라고 하는 것 같습니다.

혹시 해결방안 있으면 자유롭게 말씀해주세요!!

**Comment by mentalese** [comment]
정확한 상황을 알면 좋을것 같은데요. 클라이언트(브라우저)에서 바로 호출을 하신 걸까요? 
브라우저 -> 서버 -> OpenAPI 을 통하는 방식으로 처리하는 방식으로 해결을 많이 하긴 합니다.
